### ISSUE TITLE
Make Scene

### ISSUE THREAD

**Issue by namse** [skatpgusskat/overview#1]
# The Scene is

Scene is the same with XSplit's Scene.

Every Scene has frames' information.

Overview only open one scene at once.
If you change, every frame will move or removed by scene's information.

# What To do 

Implement below things.
- [x] Define Scene
- [x] Save Scene Data
- [x] Change Scene

**Comment by namse** [comment]
# Scene is...

- Background Stuff
- Array of Frame Location

# Changing Scene is...

Changing scene from prevScene to nextScene.
On frame in prevScene,
- if frame doesn't exist in nextScene
  - Remove that window(frame window).
- If frame exists in nextScene
  - Move location to nextScene's Frame's location.

On  frame in nextScene,
- only if frame doesn't exist in prevScene
  - Create Frame.

**Comment by namse** [comment]
# on the Data Perspective

- Frame Data (is array of Frame)
  - Frame
    - Id
    - Frame Options

- Scene Data
  - Frame Position & Size
    - Frame Id
    - Position(x, y)
    - Size(width, height)


Example in yml,

```yaml
frames:
  - id: 1
    type: Pdf
    src: https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf

scenees:
  - sceneName: main
    frames:
    - id: 1
      x: 0
      y: 0
      width: 960
      height: 540
````
